### PR TITLE
Add german translation and fix typo in english translation

### PR DESCRIPTION
**Pull request by Lekuruu**
Here is a German translation for Nerinyan. I used a lot of reference from the official site, since there are a lot of hard-to-translate words. I didn't spellcheck it *yet*, so please don't merge it directly.

I also fixed a typo in the English translation ("ben" -> "been").

For everyone who speaks German, I have some questions:

1. Should we use the casual form `du` or `sie` instead?
2. Is the `not_found_message` a little bit too harsh, or is it okay?
3. I am not sure if we should use `Archiv` or `Zip`...
4. Should a beatmap be addressed with `diese beatmap`, or `dieser beatmap`?
    (Both sound kinda wierd to me...)

### CODE REVIEW

**Comment by Lekuruu** [comment]
I think everything should be fine now...

**Comment by zeee2** [comment]
lgtm

**Comment by zeee2** [comment]
can you translate lines 144-148?

**Comment by Lekuruu** [comment]
I can work on it in a few hours

**Pull request merged**
